import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata = {
  title: "Inicio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}><Navbar/>{children}</body>
    </html>
  );
}
